name: Python Lint and Test
on:
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.10']

    permissions:
      contents: read
      pull-requests: write
      
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pipenv
        pipenv install -d --deploy

    - name: Run Linter
      run: |
        {
          echo 'MESSAGE<<EOF'
          pipenv run pylint main.py --exit-zero
          echo EOF
        } >> "$GITHUB_ENV"

    # Post Results to PR only on pull_request
    - name: Post result to PR
      if: github.event_name == 'pull_request'
      uses: mshick/add-pr-comment@v2
      with:
        message: ${{ env.MESSAGE }}
